project:
  type: website
  output-dir: docs
website:
  title: "Romuald ZAMI"
  description: "Site web/Blog"
  favicon: "images/Purple tree.png"
  twitter-card:
    creator: "@Romuald"
  site-url: https://robertmitchellv.com
  repo-url: https://github.com/robertmitchellv/robertmitchellv.github.io
  repo-actions: [edit, issue]
  navbar:
    title: false
    logo: "images/Purple tree.png"
    background: primary
    search: true
    left:
      - text: "{{< fa house-user >}} Accueil"
        href: index.qmd
      - text: "{{< fa laptop-code >}} Blog"
        href: blog.qmd
      - text: "{{< fa chalkboard-user >}} Talks"
        href: talks.qmd
      - text: "{{< fa chart-line >}} Projects"
        href: projects.qmd
      - text: "{{< fa address-card >}} About"
        href: about.qmd
      - text: "{{< fa paperclip >}} Vitae"
        href: vitae.qmd
      - text: "{{< fa paper-plane >}} Contact"
        href: mailto:romu.zami@gmail.com
    right:
      - icon: github
        href: https://github.com/robertmitchellv
      - icon: twitter
        href: https://twitter.com/Romu_Zam
      - icon: linkedin
        href: https://linkedin.com/in/robertmitchellv
  page-footer:
    background: primary
    left: "{{< fa user-circle >}} 2022 - Romuald ZAMI"
    center:
      - text: "<img src='/images/animation_transparent.png' width='auto' height='60px'>"
    right:
      - icon: github
        href: https://github.com/robertmitchellv
      - icon: twitter
        href: https://twitter.com/Romu_Zam
      - icon: linkedin
        href: https://linkedin.com/in/robertmitchellv

format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom-dark.scss]

freeze: true
